### ISSUE TITLE
packageName

### ISSUE THREAD

**Issue by nutgaard** [navikt/react-intl-bundler#3]
@erlendev Burde vi teste ut `@navikt`-scopet på nye pakker? 
E.g rename denne til `@navikt/react-intl-bundler`?

**Comment by erlendev** [comment]
Det kan vi absolutt gjøre. Trenger dere noe hjelp fra meg eller Eirik til dette?

@Lillebo @nutgaard

**Comment by nutgaard** [comment]
Om TravisCI har npm_token så burde det ikke være nødvendig med noen endringer fra deres side. Men jeg har ikke ikke prøvd å publisere noen av nav-pakkene manuelt tidligere, så kan hende det er noe som trengs fra dere.

**Comment by erlendev** [comment]
Jeg har ikke registrert npm_token i Travis, kun i Circle, så tipper det ikke ligger inne der. Men det kan jeg fikse hvis jeg får en link til et sted hvor jeg skal legge den inn. 

Men med det tokenet på plass i CI-en vil jeg vel tro at dere slipper å publisere pakken manuelt? 

Edit: Da vil det vel kanskje holde å bare kjøre `npm publish --access public` i pipelinen deres, gitt at Travis setter npm-tokenet riktig. Jeg antar at det er noe tilsvarende det som skjer internt i lerna i `nav-frontend-moduler`-pipelinen.

**Comment by etse** [comment]
Tenker diskusjon om travis/circleci kan gjøres i #1 :)
Enig i navnbytte, så endret til `@navikt/react-intl-bundler`
